#!/usr/bin/env bash
#$ -S /usr/bin/env bash
#$ -cwd
#$ -j Y
#$ -V
#$ -pe smp 5
#
# https://askubuntu.com/questions/39309/how-do-i-find-the-version-of-bash-i-am-running
if [ -z `echo ${BASH}` ]; then
  echo "Make sure \"bash\" >v4.0 is installed"
  exit 1
else
  if ((BASH_VERSINFO[0] < 4)); then 
    echo "Sorry, you need at least bash-4.0 to run this script." >&2
    exit 1
  fi
fi
job="bash"

# Allocate input arguments to variables
#
OW=""                 # multiple (overwrite mode)
verb_flag=""          # multiple (turn on verboses)
FREEVIEW=""           # spinoza_bestvertex
VERT=""               # spinoza_bestvertex
PROC=""               # spinoza_brainextraction
raw_flag=""           # spinoza_denoising
SGE=""                # spinoza_denoising/spinoza_nordic/spinoza_linerecon/spinoza_registration
COMB_ONLY=""          # spinoza_extractregions
CLIP=""               # spinoza_fitprfs
CLIP_FLAG=""          # spinoza_fitprfs
TASK_ID=""            # spinoza_fitprfs
MODEL=""              # spinoza_fitprfs
GRID=""               # spinoza_fitprfs
MULTIPLE_DESIGNS=""   # spinoza_fitprfs
FIT_HRF=""            # spinoza_fitprfs
psc_flag=""           # spinoza_fitprfs
zscore_flag=""        # spinoza_fitprfs
raw_flag=""           # spinoza_fitprfs
use_constr=""         # spinoza_fitprfs
fit_flag=""           # spinoza_fitprfs
fprep_input=0         # spinoza_fitprfs
use_bbr=""            # spinoza_fmriprep
WARP_ONLY=""          # spinoza_fmriprep
REMOVE_WF=""          # spinoza_fmriprep
run_local=""          # spinoza_fmriprep/spinoza_fitprfs
LAYER_FLAG=""         # spinoza_layering
GDH_FLAG=""           # spinoza_mgdm
REG_TYPE=""           # spinoza_registration
DRAW_SAG="itk"        # spinzoa_sagittalsinus
SES_TYPE=""           # spinoza_scanner2bids
ADD_INV=""            # spinoza_scanner2bids
UPs=""                # spinoza_qmrimaps
NO_BIAS=""            # spinoza_qmrimaps

# use long options in bash:
# https://stackoverflow.com/questions/402377/using-getopts-to-process-long-and-short-command-line-options
declare -a array=("--no_bbr" "--local" "--ups" "--no_biascorr" "--remove_wf" "--remove_surf_wf" "--sge" "--no_freeview" "--comb_only" "--grid" "--multi_design" "--hrf" "--rigid" "--syn" "--affine" "--lines" "--gdh" "--nighres" "--surface" "--warp_only" "--no_raw" "--verbose" "--zcore" "--full" "--no_clip" "--tc" "--bgfs" "--inv" "--no_fit" "--fmriprep" "--fprep")

# sort options array
IFS=$'\n' opts=($(sort <<<"${array[*]}"))
unset IFS

while getopts :-:wjqom:s:h:n:t:l:v:p:x:u:r:e:i:c: arg
do
  case ${arg} in
    -)
      case "${OPTARG}" in
        no_bbr)
          use_bbr="--no_bbr"
          ;;
        local)
          run_local="--local"
          ;;
        ups)
          UPs="-u"
          ;;
        no_biascorr)
          NO_BIAS="-b"
          ;;
        remove_wf)
          REMOVE_WF="-r all"
          ;;
        remove_surf_wf)
          REMOVE_WF="-r surf"
          ;;    
        sge)
          SGE="--sge"
          ;;       
        no_freeview)
          FREEVIEW="--no_freeview"
          ;;      
        comb_only)
          COMB_ONLY="-c"
          ;;            
        grid)
          GRID="--grid"
          ;;        
        itk)
          DRAW_SAG="itk"
          ;;        
        fsl)
          DRAW_SAG="fsl"
          ;;           
        freeview)
          DRAW_SAG="fv"
          ;;    
        multi_design)
          MULTIPLE_DESIGNS="--multi_design"
          ;;   
        hrf)
          FIT_HRF="--hrf"
          ;;
        rigid)
          REG_TYPE="--rigid"
          ;;
        syn)
          REG_TYPE="--syn"
          ;;
        affine)
          REG_TYPE="--affine"
          ;;
        lines)
          SES_TYPE="--lines"
          ;;     
        gdh)
          GDH_FLAG="--gdh"
          ;;
        nighres)
          LAYER_FLAG="nighres"
          ;;
        surface)
          LAYER_FLAG="surface"
          ;;       
        warp_only)
          WARP_ONLY="--warp_only"
          ;;                    
        psc)
          psc_flag="--psc"
          ;;      
        raw)
          raw_flag="--raw"
          ;;                 
        no_raw)
          raw_flag="--no_raw"
          ;;        
        verbose)
          verb_flag="--verbose"
          ;;         
        zscore)
          zscore_flag="--zscore"
          ;;     
        full)
          PROC="--full"
          ;;         
        no_clip)
          CLIP="--no_clip"
          ;;
        tc)
          use_constr="--tc"
          ;;
        bgfs)
          use_constr="--bgfs"
          ;;          
        inv)
          ADD_INV="--inv"
          ;;        
        no_fit)
          fit_flag="--no_fit"
          ;;         
        fprep)
          fprep_input=1
          ;;
        fmriprep)
          fprep_input=1
          ;;          
        *)
          if [ "$OPTERR" = 1 ] && [ "${optspec:0:1}" != ":" ]; then
            echo "Unknown option --${OPTARG}, possible options are:"
            for ii in ${opts[@]}; do echo " ${ii}"; done
            echo "Enter \"`basename ${0}`\" what these flags do"
            exit 1
          fi
          ;;
      esac;;  
    m)  MOD=${OPTARG}
          ;;
    s)  SUB=${OPTARG}
          ;;
    h)  HEMI=${OPTARG}
          ;;
    n)  SES=${OPTARG}
          ;;
    o)  OW="-o"
          ;;
    t)  TYPE=${OPTARG}
          ;;
    l)  WHICH_MOD=${OPTARG}
          ;;
    v)  VERTICES=${OPTARG}
          ;;
    p)  PRF_MODEL=${OPTARG}
          ;;
    c)  C_FLAG=${OPTARG}
          ;;
    x)  KWARGS=${OPTARG}
          ;;
    u)  CONF=${OPTARG}
          ;;
    r)  ROI=${OPTARG}
          ;;       
    e)  n_echoes=${OPTARG}
          ;;
    i)  images=${OPTARG}
          ;;             
  esac
done

# source helper functions
source call_bashhelper

# set the execute flag
FLAG_executeModule="${MOD}"

start=`date +%s`
start_date=`date`

#---------------------------------------------------------------------------------------------------------
# Create help text
function Usage {
    cat <<USAGE

===================================================================================================
                            MASTER SCRIPT FOR LINE SCANNING ANALYSIS
===================================================================================================

Main script governing all (pre-)processing steps for high resolution anatomical data, as well as 
whole-brain fMRI data analyses (specifically population receptive field [pRF]) and linescanning
data. All modules can be called with master -m <module>, which in it's bare form with loop through
the subjects it can find in the specified input directories. You can also include an -s flag to 
process a single subject. See below for additional settings. Please read through it's module what
it's default settings are and what you'd need to do to get it running for you.

Have fun!

Args:
  -c                List used for clipping of design matrix. Format must be:
                    [<top>,<bottom>,<left>,<right>]
  -e <n_echoes>     Specify the amount of echoes of the acquisition
  -h <hemisphere>   used for lineplanning, denotes which hemisphere to process
  -i <image path>   specify custom path to PNG's for pRF-fitting. This allows deviation from the 
                    standard path that 'spinoza_fitprfs' will be looking for
  -l <which mod>    look for a module number given a string to search for (e.g., master -l layer); can
                    also be used with:
                    - spinoza_bestvertex to use a particular label-file (default = V1_exvivo.thresh).
                      If label file is being specified, the following applies:
                        - File must live in SUBJECTS_DIR/<subject>/label
                        - File must be preceded by '?h.', representing a file for both hemispheres 
                          separately
                        - Can be either a FreeSurfer-defined label file or gitfi-files (e.g., 'handknob
                          _fsnative.gii' means there's a 'lh.handknob_fsnative.gii' and 'rh.handknob_
                          fsnative.gii' file)
  -m <module>       always required, specifies which module to run. Multiple modules should be com-
                    ma separated
  -n <session>      session nr, used to create file structure according to BIDS. Specify '-n none' if 
                    you don't want to differentiate between sessions
  -o                turn on overwrite mode; removes subject-specific directories or crucial files so 
                    that the process is re-ran.
  -p <prf_model>    switch to specify what type of model to use for the pRF-modeling. Enabled for spi-
                    noza_fitprfs & spinoza_bestvertex
  -q <info mod>     query the usage-information of a given module number: e.g., master -m 00 -q
                    brings up the help-text from module 00 (spinoza_lineplanning)
  -r <roi>          Set label file for 'spinoza_bestvertex' or ROI for 'spinoza_extractregions'
  -s <subject>      Subject ID (e.g., 01). Can also be comma-separated list: 01,02,05
  -t <type|task>    used for;
                      - spinoza_fmriprep: to run either the 'anat' workflow only, or also include func
                        data ('func') or a direct task-identifier such as '${TASK_SES1[0]}'
                      - spinoza_fitprfs: limit pRF-fitting to a given task. You can also specify multi-
                        ple tasks if you want to bypass the setup file completely. In that case, use 
                        the format '-t <task1>,<task2>,<task3>'. If you use this option, please still 
                        use '--multi_design' to select the correct log-directory
                      - spinoza_bestvertex: select pRF-parameters from specific task
  -u <config>       specify configuration file for fMRIprep (see linescanning/misc for examp-
                    les). If not specified, no configuration will be used. If ses-1 is specified,
                    linescanning/misc/fmriprep_config.json is used; above that, fmriprep_con-
                    fig2.json is used. Enter '-u none' if you have multiple sessions and you want
                    to process everything without filtering
  -v <vertices>     manually insert vertices to use as "best_vertex" (module 18). Should be format-
                    ted as -v "lh,rh" (please use two vertices; one for left hemi and one for right
                    hemi > makes life easier)
  -w <wagstyl>      Use Wagstyl's equivolumetric layering for layerification. Use Nighres otherwise
                    accepted options are 'gauss' for Gaussian model, and 'norm' for Normalization
                    model. Should/can be use for module 17, pRF-fitting
  -x <kwargs>       Can be used for a variety of options by setting it to ANYTHING other than empty. 
                    Usages include:
                      - spinoza_profiling; specify the type of file to use
                      - spinoza_fitprfs; specify the constraints to use for fitting. Should be format-
                        ted as -x "<gaussian>,<extended>". E.g., '-x tc,bgfs'
  --affine          use 'affine'-registration (spinoza_registration)
  --bgfs            use L-BGFS minimization for both the Gaussian as well as the extended model (e.g.,
                    DoG, CSS, or DN). By default, we'll use trust-constr minimization for both. It's
                    recommended to at least to Gaussian fitting with trust-constr, and potential ex-
                    tended models with L-BGFS. For this, see '-x' flag
  --comb_only       skip nighres, only do combination of segmentations. Works with '-o' flag. 
  --f(mri)prep      use output from fMRIPrep as input for pRF-fitting. Default is the output fro py-
                    best
  --full            Do full processing with CAT12, assuming module 8 was skipped. This does itera-
                    tive SANLM-filtering, bias correction, and intensity normalization. Can some-
                    times be overkill, so generally we use CAT12 for the additional segmentations
                    and brain extraction
  --fv              use FreeView to draw sinus mask (spinoza_sagittalsinus) 
  --fsl             use FSLeyes to draw sinus mask (spinoza_sagittalsinus) 
  --gdh             use custom implementation of MGDM (via call_gdhmgdm) that also considers extra
                    filter files. By default we'll use call_nighresmgdm, which includes the T1w/T1map
                    files
  --grid            maps to '-g' in spinoza_fitprfs; runs gridfit only
  --hrf             also fit the HRF during pRF-fitting (spinoza_fitprfs)
  --itk             use ITK-Snap to draw sinus mask (spinoza_sagittalsinus) [default]
  --inv             in case a session contains line-scanning data but also high resolution anatomical
                    data that you'd like to process as per usual, use this flag to also copy in the
                    INV1/INV2 images into the 'anat'-folder of the session. This will allow you to 
                    run spinoza_qmrimaps as usual.
  --lines           specifies that we're dealing with a line-scanning session (spinoza_scanner2bids). 
                    Uses a custom pipeline for converting the files in a veeery specific way. If not
                    specified, we'll assume a regular scan-session of whole-brain data.
  --local           maps to '-l' in spinoza_fmriprep & spinoza_fitprfs; runs the process locally.
  --multi_design    specifies that for all runs in the dataset have run-/task-specific screenshot direc-
                    tories. This requires that the directory names you saved must match your naming 
                    scheme of functional files as we'll match on run-/task-ID (spinoza_fitprfs)
  --nighres         use nighres-software for cortex reconstruction (spinoza_cortexrecon) or equivolu-
                    metric layering (spinoza_layering)
  --no_bbr          maps to '--force-no-bbr' in call_fmriprep
  --no_biascorr     maps to '-b' in spinoza_biassanlm; don't perform bias correction after denoising
  --no_clip         spinoza_fitprfs; ensures that the design matrix is NOT clipped, despite the possible
                    presence of screen delimiter files
  --no_fit          spinoza_fitprfs; stop right after saving out averaged data. This was useful for me 
                    to switch to percent-signal change without requiring a re-fit.                    
  --no_freeview     disable FreeView during vertex selection (spinoza_bestvertex)
  --ups             maps to '-u' in spinoza_qmrimaps; turn on Universal Pulses
  --remove_wf       maps to '-r all' in spinoza_fmriprep; removes full fmriprep_wf folder. Be careful
                    with this one! Mainly used for debugging of a single subject. Use \"--remove_surf_wf\"
                    to specifically remove the surface reconstruction folder when you have new FreeSurfer
                    output that fMRIPrep needs to use
  --remove_surf_wf  Remove surface reconstruction workflow folder; refreshes the surfaces used for regi-
                    stration and transformation
  --rigid           use 'rigid-body' registration (spinoza_registration)
  --sge             passes '--sge' on to:
                      -spinoza_linerecon
                      -spinoza_denoising
                      -spinoza_nordic
                      -spinoza_registration
                    submits jobs to cluster
  --surface         use Wagstyl's equivolumetric layering function
  --syn             use 'syn'-registration (spinoza_registration)
  --tc              use trust-constr minimization for both the Gaussian as well as the extended model (e.g.,
                    DoG, CSS, or DN). By default, we'll use trust-constr minimization for both. It's
                    recommended to at least to Gaussian fitting with trust-constr, and potential ex-
                    tended models with L-BGFS. For this, see '-x' flag  
  --verbose         turn on verbose for pRF-fitting (spinoza_fitprfs)
  --warp_only       spinoza_fmriprep; skip full processing, but make new 'boldref'-images and copy bold-
                    to-T1w registration files

Usage:
  master -m <MODULES TO RUN>
  master -m 01,02,03,04 (comma-separated for running multiple modules in succession)
  master -m 00 -q   (print help-text of module 00)
  master -l mgdm    (fetch module number mgdm-module)
  master -m 02 -n 2 --lines (line-scanning session)
  master -m 02 -n 2 --lines --inv (line-scanning session + high resolution anatomies)
  master -m 15 -t func (run fMRIPrep on available tasks)
  master -m 15 -t scenes (run fMRIPrep on scenes-task only)
  master -m 17 -p norm (run pRF-fitting with Normalization model)

Additional options:
  - Specify a subject to run (for certain modules):   master -m <module> -s <subj-ID>
  - Specify a hemisphere (for certain modules):       master -m <module> -h left
  - Disable overwrite mode (for certain modules):     master -m <module> -o n
  - Specify a particular session to use:              master -m <module> -n 1
  - Specify processing type fMRIprep (anat|func)      master -m <module> -t anat

Available modules:                                     Script                           hh:mm:ss
  -00:  Register anat ses-1 to ms ses-1 for planning   (spinoza_lineplanning)           00:06:00
  -01:  Make new session for subject                   (spinoza_bidssession)            00:00:01
  -02:  Convert raw files to nifti                     (spinoza_scanner2bids)           00:02:00
  -03:  Reconstruction of line data                    (spinoza_linerecon)              00:10:00
  -04:  Estimate T1's from mp2rage and memp2rage       (spinoza_qmrimaps)               00:01:30
  -05a: Register T1 from memp2rage to T1 from mp2rage  (spinoza_registration)           00:03:00
  -05b: Register T1 from mp2rage to MNI152             (spinoza_registration)           01:05:00
  -06:  Average T1w/T1map from MP2RAGE & MP2RAGEME     (spinoza_averageanatomies)       00:02:00
  -07:  Make sinus mask from T1w/T2w ratio             (spinoza_sinusfrommni)           00:03:00
  -08:  Bias correction + SANLM denoising              (spinoza_biassanlm)              00:07:00
  -09:  Brain extract (CAT12 || ANTs || FSL)           (spinoza_brainextraction)        00:10:00
  -10:  NORDIC denoising of whole-brain data           (spinoza_nordic)                 00:05:00
  -11:  Dura estimation and skull estimations          (spinoza_dura)                   00:08:00
  -12:  Create mask of sagittal sinus                  (spinoza_sagittalsinus)          00:03:00
  -13:  Combine all masks and apply to average         (spinoza_masking)                00:02:30
  -14:  Surface segmentation with FreeSurfer           (spinoza_freesurfer)             09:30:00
  -15:  Preprocessing with fMRIprep                    (spinoza_fmriprep)               14:00:00
  -16:  Data denoising with pybest                     (spinoza_denoising)              00:05:00
  -17:  pRF-fitting with pRFpy                         (spinoza_fitprfs)                00:07:00
  -18:  Determine best vertex with pycortex            (spinoza_bestvertex)             00:01:30
  -19:  Tissue segmentation with FAST                  (spinoza_segmentfast)            00:17:00
  -20:  Tissue segmentation with MGDM                  (spinoza_mgdm)                   00:11:45
  -21:  Region extraction with nighres                 (spinoza_extractregions)         00:02:00
  -22:  Cortex reconstruction with nighres             (spinoza_cortexrecon)            00:05:30
  -23:  Layering with nighres/surface_tools            (spinoza_layering)               00:07:30
  -24:  Subcortex parcellation with nighres            (spinoza_segmentsubcortex)       00:10:00
  -25:  Project line to surface                        (spinoza_line2surface)           00:02:00
  -26:  Sample a dataset across depth with Nighres     (spinoza_profiling)              00:20:00

--END--
---------------------------------------------------------------------------------------------------

USAGE
    exit 1
}


#---------------------------------------------------------------------------------------------------
# Error handling
if [[ $# -lt 2 ]] ; then
  echo
  echo "NEED AT LEAST ONE MODULE. echoING HELP AND EXITING"
  Usage >&2
  exit 1
fi

#---------------------------------------------------------------------------------------------------
# Check for which-module switch 
if [[ ! -z ${WHICH_MOD} ]] && [[ "${@}" != *"-m"* ]]; then
  mod_nr=`get_module_nr ${WHICH_MOD}`
  if [[ ! -z ${mod_nr} ]]; then
    echo "module ${mod_nr} contain(s) \"${WHICH_MOD}\""
  else
    echo "could not find a module associated with \"${WHICH_MOD}\""
  fi
fi

#---------------------------------------------------------------------------------------------------------
# source setup
call_loadsetup

#---------------------------------------------------------------------------------------------------
# Define default session/subject stuff
if [[ -z ${SES} ]]; then
  # Going to assume ses-1 here
  SESSION="-n 1"
elif [[ ${SES,,} == "none" ]]; then
  SESSION=""
else
  SESSION="-n ${SES}"
fi

if [[ -z ${SUB} ]]; then
  SUBJECT=""
else
  SUBJECT="-s ${SUB}"
fi

#---------------------------------------------------------------------------------------------------
# STEP 00: Optimal line planning procedure with registration of anat ses-1 to ms ses-2
module=00

# Check whether the module should be executed
echo ${FLAG_executeModule} | grep -q ${module}
if [[ $? -eq 0 ]]; then

  if [[ "${@}" == *"-q"* ]]; then
    ${job} spinoza_lineplanning
    exit 1
  fi

  echo "---------------------------------------------------------------------------------------------------"
  echo "[${module}] Optimal line planning procedure with registration of anat ses-1 to ms ses-X"

  if [[ -z ${SUB} ]]; then
    echo "ERROR: Need a subject number for this module. Specify the subject number with the -s flag in the master script"
    echo "  e.g., ./master -m 00 -s 001"
    exit 1
  fi

  if [[ -z ${HEMI} ]]; then
    echo "ERROR: Need a hemisphere for this module. Specify the subject number with the -h flag in the master script"
    echo "  e.g., ./master -m 00 -s 001 -h left"
    exit 1
  fi

  if [[ -z ${SES} ]]; then
    read -p "Session number not specified; defaulting to \"ses-2\". Sure you want to continue..? (y/n)? " choice
    case "${choice}" in
      y|Y ) c=1;;
      n|N ) c=0;;
      * ) c="invalid";;
    esac

    if [[ ${c} -eq 1 ]]; then
      ses_nr=2
    elif [[ ${c} == "invalid" ]]; then
      echo "Your answer was invalid. Quitting.. Use \"-n X\" to specify your desired session"
      exit 1
    else
      echo "You selected \"no\". Quitting.. Use \"-n X\" to specify your desired session"
      exit 1
    fi
  else
    ses_nr=${SES}
  fi
  
  subject=${SUBJECT_PREFIX}${SUB}
  ${job} spinoza_lineplanning ${OW} \
                              -s ${subject} \
                              -n ${ses_nr} \
                              -i ${DIR_DATA_SOURCE}/${subject}/ses-${ses_nr}/planning \
                              -p ${DIR_DATA_DERIV}/pycortex/${subject}/line_pycortex.csv \
                              -h ${HEMI}


  echo "[${module}] DONE" && echo

fi

#---------------------------------------------------------------------------------------------------
# STEP 01: Make new session for subject
module=01

# Check whether the module should be executed
echo ${FLAG_executeModule} | grep -q ${module}

if [[ $? -eq 0 ]]; then

  if [[ "${@}" == *"-q"* ]]; then
    ${job} spinoza_bidssession
    exit 1
  fi

  echo "---------------------------------------------------------------------------------------------------"
  echo "[${module}] Create folder structure for new session"

  if [[ -z ${SUB} ]]; then
    echo "ERROR: Need a subject number for this module. Specify the subject number with the -s flag in the master script"
    echo "  e.g., ./master -m 01 -s 001"
    exit 1
  fi

  if [[ -z ${SES} ]]; then
    echo "ERROR: Need a session number for this module. Specify the subject number with the -n flag in the master script"
    echo "  e.g., ./master -m 01 -n 1"
    exit 1
  fi

  ${job} spinoza_bidssession ${SUB} ${SES}\

  echo "[${module}] DONE"

fi

#---------------------------------------------------------------------------------------------------
# STEP 02: Convert raw files to nifti
module=02

# Check whether the module should be executed
echo ${FLAG_executeModule} | grep -q ${module}

if [[ $? -eq 0 ]]; then

  if [[ "${@}" == *"-q"* ]]; then
    ${job} spinoza_scanner2bids
    exit 1
  fi

  echo "---------------------------------------------------------------------------------------------------"
  echo "[${module}] Convert raw files to nifti"


  ${job} spinoza_scanner2bids ${SES_TYPE} ${SUBJECT} ${SESSION} ${OW} ${ADD_INV} ${DIR_DATA_HOME} ${DIR_DATA_SOURCE}

  echo "[${module}] DONE" && echo

fi

#---------------------------------------------------------------------------------------------------
# STEP 03: Reconstruct line-data (scripts Luisa)
module=03

# Check whether the module should be executed
echo ${FLAG_executeModule} | grep -q ${module}

if [[ $? -eq 0 ]]; then

  if [[ "${@}" == *"-q"* ]]; then
    ${job} spinoza_linerecon
    exit 1
  fi

  echo "---------------------------------------------------------------------------------------------------"
  echo "[${module}] Reconstruct line data with MRecon"

  if [[ -z ${n_echoes} ]]; then
    N_ECHOES=""
  else
    N_ECHOES="-m ${n_echoes}"
  fi    

  ${job} spinoza_linerecon ${SUBJECT} ${SESSION} ${N_ECHOES} ${OW} ${SGE} ${DIR_DATA_HOME} ${DIR_DATA_SOURCE}

  if [[ $? -ne 0 ]]; then
    echo "ERROR in master: spinoza_linerecon exited with non-zero status"
    exit 1
  fi

  echo "[${module}] DONE" && echo

fi

#---------------------------------------------------------------------------------------------------
# STEP 04: Estimate T1's from mp2rage and memp2rage and do some multiparametric mapping
module=04

# Check whether the module should be executed
echo ${FLAG_executeModule} | grep -q ${module}

if [[ $? -eq 0 ]]; then

  if [[ "${@}" == *"-q"* ]]; then
    ${job} spinoza_qmrimaps
    exit 1
  fi

  echo "---------------------------------------------------------------------------------------------------"
  echo "[${module}] Multiparametric mapping"

  ${job} spinoza_qmrimaps ${SUBJECT} ${SESSION} ${OW} ${UPs} ${DIR_DATA_HOME} ${DIR_DATA_DERIV}/pymp2rage

  if [[ $? -ne 0 ]]; then
    echo "ERROR in master: spinoza_qmrimaps exited with non-zero status"
    exit 1
  fi

  echo "[${module}] DONE" && echo

fi

#---------------------------------------------------------------------------------------------------
# STEP 05a: Register T1 from memp2rage to T1 from mp2rage
module=05a

# Check whether the module should be executed
echo ${FLAG_executeModule} | grep -q ${module}

if [[ $? -eq 0 ]]; then

  if [[ "${@}" == *"-q"* ]]; then
    ${job} spinoza_registration
    exit 1
  fi

  echo "---------------------------------------------------------------------------------------------------"
  echo "[${module}] Register T1 from memp2rage to T1 from mp2rage"

  if [[ ${DATA:u} == "AVERAGE" ]]; then

    # check where inputs live
    if [[ -d ${DIR_DATA_DERIV}/pymp2rage ]]; then
      INPUT_DIR=${DIR_DATA_DERIV}/pymp2rage
    else
      INPUT_DIR=${DIR_DATA_HOME}
    fi

    ${job} spinoza_registration ${REG_TYPE} ${SUBJECT} ${OW} ${SESSION} ${SGE} ${INPUT_DIR} ${DIR_DATA_DERIV}/ants

    if [[ $? -ne 0 ]]; then
      echo "ERROR in master: spinoza_registration exited with non-zero status"
      exit 1
    fi

  else
    echo "The variable \"DATA\" is \"${DATA}\"; must be \"AVERAGE\" for this module."
  fi

  echo "[${module}] DONE" && echo

fi

#---------------------------------------------------------------------------------------------------
# STEP 05b: Register T1 from mp2rage to MNI152 for sagittal sinus mask
module=05b

# Check whether the module should be executed
echo ${FLAG_executeModule} | grep -q ${module}

if [[ $? -eq 0 ]]; then

  if [[ "${@}" == *"-q"* ]]; then
    ${job} spinoza_registration
    exit 1
  fi

  echo "---------------------------------------------------------------------------------------------------"
  echo "[${module}] Register T1 from mp2rage to MNI152 for sagittal sinus mask"
  
  if [[ -d ${DIR_DATA_DERIV}/pymp2rage ]]; then
    INPUT_DIR=${DIR_DATA_DERIV}/pymp2rage
  else
    INPUT_DIR=${DIR_DATA_HOME}
  fi

  ${job} spinoza_registration ${REG_TYPE} ${SUBJECT} ${OW} ${SESSION} ${SGE} ${INPUT_DIR} ${DIR_DATA_DERIV}/ants mni

  if [[ $? -ne 0 ]]; then
    echo "ERROR in master: spinoza_registration exited with non-zero status"
    exit 1
  fi

  echo "[${module}] DONE" && echo

fi

#---------------------------------------------------------------------------------------------------
# STEP 06: Calculate averages of UNIT1, INV1, and INV2
module=06

# Check whether the module should be executed
echo ${FLAG_executeModule} | grep -q ${module}

if [[ $? -eq 0 ]]; then

  if [[ "${@}" == *"-q"* ]]; then
    spinoza_averageanatomies
    exit 1
  fi

  echo "---------------------------------------------------------------------------------------------------"
  echo "[${module}] Calculate averages of the T1-weighted image and T1map"

  if [[ ${DATA^^} == "AVERAGE" ]]; then

    if [[ -d ${DIR_DATA_DERIV}/pymp2rage ]]; then
      INPUT_DIR=${DIR_DATA_DERIV}/pymp2rage
    else
      INPUT_DIR=${DIR_DATA_HOME}
    fi  

    spinoza_averageanatomies ${SUBJECT} ${SESSION} ${INPUT_DIR} ${DIR_DATA_DERIV}/pymp2rage

    if [[ $? -ne 0 ]]; then
      echo "ERROR in master: spinoza_averageanatomies exited with non-zero status"
      exit 1
    fi

  else
    echo "The variable \"DATA\" is \"${DATA}\"; must be \"AVERAGE\" for this module."
  fi

  echo "[${module}] DONE" && echo

fi

#---------------------------------------------------------------------------------------------------
# STEP 07: Create sagittal sinus mask using the MNI-mask & T1w/T2w-ratio
module=07

# Check whether the module should be executed
echo ${FLAG_executeModule} | grep -q ${module}

if [[ $? -eq 0 ]]; then

  if [[ "${@}" == *"-q"* ]]; then
    ${job} spinoza_sinusfrommni
    exit 1
  fi

  echo "---------------------------------------------------------------------------------------------------"
  echo "[${module}] Create sagittal sinus mask using the MNI-mask & T1w/T2w-ratio"

  if [[ -d ${DIR_DATA_DERIV}/pymp2rage ]]; then
    INPUT_DIR=${DIR_DATA_DERIV}/pymp2rage
  else
    INPUT_DIR=${DIR_DATA_HOME}
  fi

  ${job} spinoza_sinusfrommni ${SUBJECT} ${SESSION} ${OW} ${INPUT_DIR} ${DIR_DATA_DERIV}/ants ${DIR_DATA_DERIV}/manual_masks

  if [[ $? -ne 0 ]]; then
    echo "ERROR in `basename ${0}`: spinoza_sinusfrommni exited with non-zero status"
    exit 1
  fi

  echo "[${module}] DONE" && echo

fi

#---------------------------------------------------------------------------------------------------
# STEP 08: Perform bias field correction with ANTs' N4 algorithm on INV2
module=08

# Check whether the module should be executed
echo ${FLAG_executeModule} | grep -q ${module}

if [[ $? -eq 0 ]]; then

  if [[ "${@}" == *"-q"* ]]; then
    ${job} spinoza_biassanlm
    exit 1
  fi

  echo "---------------------------------------------------------------------------------------------------"
  echo "[${module}] Perform bias field correction and SANLM-filtering"
  
  if [[ -d ${DIR_DATA_DERIV}/pymp2rage ]]; then
    INPUT_DIR=${DIR_DATA_DERIV}/pymp2rage
  else
    INPUT_DIR=${DIR_DATA_HOME}
  fi

  ${job} spinoza_biassanlm ${SUBJECT} ${SESSION} ${NO_BIAS} ${INPUT_DIR} ${DIR_DATA_DERIV}/denoised

  if [[ $? -ne 0 ]]; then
    echo "ERROR in `basename ${0}`: spinoza_biassanlm exited with non-zero status"
    exit 1
  fi

  echo "[${module}] DONE" && echo

fi

#---------------------------------------------------------------------------------------------------
# STEP 09: Brain extraction
module=09

# Check whether the module should be executed
echo ${FLAG_executeModule} | grep -q ${module}

if [[ $? -eq 0 ]]; then

  if [[ "${@}" == *"-q"* ]]; then
    ${job} spinoza_brainextraction
    exit 1
  fi

  echo "---------------------------------------------------------------------------------------------------"
  echo "[${module}] Brain extract MP2RAGE-INV2 with ANTs|FSL|CAT12"

  DO_STUFF="cat12"
  if [[ ${DO_STUFF} ==  "inv2" ]]; then
    ${job} spinoza_brainextraction ${SUBJECT} ${SESSION} ${DIR_DATA_DERIV}/ants ${DIR_DATA_DERIV}/skullstripped ${DIR_DATA_DERIV}/manual_masks FSL
  elif [[ ${DO_STUFF} == "cat12" ]]; then
    ${job} spinoza_brainextraction ${SUBJECT} ${SESSION} ${OW} ${PROC} ${DIR_DATA_DERIV}/denoised ${DIR_DATA_DERIV}/cat12 ${DIR_DATA_DERIV}/manual_masks cat12
  fi

  if [[ $? -ne 0 ]]; then
    echo "ERROR in master: spinoza_brainextraction exited with non-zero status"
    exit 1
  fi

  echo "[${module}] DONE" && echo

fi

#---------------------------------------------------------------------------------------------------
# STEP 10: Do noise level estimation with AFNI's automask function
module=10
module_name="spinoza_nordic"

# Check whether the module should be executed
echo ${FLAG_executeModule} | grep -q ${module}

if [[ $? -eq 0 ]]; then

  if [[ "${@}" == *"-q"* ]]; then
    ${job} ${module_name}
    exit 1
  fi

  echo "---------------------------------------------------------------------------------------------------"
  echo "[${module}] NORDIC denoising"

  ${job} ${module_name} ${SGE} ${SUBJECT} ${SESSION} ${DIR_DATA_HOME}
  if [[ $? -ne 0 ]]; then
    echo "ERROR in master: ${module_name} exited with non-zero status"
    exit 1
  fi

  echo "[${module}] DONE" && echo

fi

#---------------------------------------------------------------------------------------------------
# STEP 11: Use nighres to get skull and dura mask
module=11

# Check whether the module should be executed
echo ${FLAG_executeModule} | grep -q ${module}

if [[ $? -eq 0 ]]; then

  if [[ "${@}" == *"-q"* ]]; then
    ${job} spinoza_dura
    exit 1
  fi

  echo "---------------------------------------------------------------------------------------------------"
  echo "[${module}] Use nighres to get skull and dura mask"

  ${job} spinoza_dura ${SUBJECT} ${SESSION} ${OW} ${DIR_DATA_DERIV}/cat12 ${DIR_DATA_HOME} ${DIR_DATA_DERIV}/nighres ${DIR_DATA_DERIV}/manual_masks

  if [[ $? -ne 0 ]]; then
    echo "ERROR in master: spinoza_dura exited with non-zero status"
    exit 1
  fi

  echo "[${module}] DONE" && echo

fi

#---------------------------------------------------------------------------------------------------
# STEP 12: Create mask of the sagittal sinus with manual edits in ITKsnap
module=12

# Check whether the module should be executed
echo ${FLAG_executeModule} | grep -q ${module}

if [[ $? -eq 0 ]]; then

  if [[ "${@}" == *"-q"* ]]; then
    ${job} spinoza_sagittalsinus
    exit 1
  fi

  echo "---------------------------------------------------------------------------------------------------"
  echo "[${module}] Create sagittal sinus mask from R2*-image"

  # DATA = MP2RAGE    > arg1 = DIR_DATA_DERIV/pymp2rage
  # DATA = MEMP2RAGE  > arg1 = DIR_DATA_DERIV/pymp2rage
  # DATA = AVERAGE    > arg1 = DIR_DATA_DERIV/ants

  ${job} spinoza_sagittalsinus ${SUBJECT} ${SESSION} ${OW} ${DIR_DATA_DERIV}/pymp2rage ${DIR_DATA_DERIV}/manual_masks ${DRAW_SAG}

  if [[ $? -ne 0 ]]; then
    echo "ERROR in master: spinoza_sagittalsinus exited with non-zero status"
    exit 1
  fi

  echo "[${module}] DONE" && echo

fi

#---------------------------------------------------------------------------------------------------
# STEP 13: Combine all masks and apply to average
module=13

# Check whether the module should be executed
echo ${FLAG_executeModule} | grep -q ${module}

if [[ $? -eq 0 ]]; then

  if [[ "${@}" == *"-q"* ]]; then
    ${job} spinoza_masking
    exit 1
  fi

  echo "---------------------------------------------------------------------------------------------------"
  echo "[${module}] Combine all masks and apply to image"

  ${job} spinoza_masking ${SUBJECT} ${SESSION} ${OW} ${DIR_DATA_DERIV}/cat12 ${DIR_DATA_DERIV}/masked_${DATA,,} ${DIR_DATA_DERIV}/manual_masks ${DIR_DATA_DERIV}/skullstripped

  if [[ $? -ne 0 ]]; then
    echo "ERROR in master: spinoza_masking exited with non-zero status"
    exit 1
  fi

  echo "[${module}] DONE" && echo

fi

#---------------------------------------------------------------------------------------------------
# STEP 14: FreeSurfer
module=14

# Check whether the module should be executed
echo ${FLAG_executeModule} | grep -q ${module}

if [[ $? -eq 0 ]]; then

  if [[ "${@}" == *"-q"* ]]; then
    ${job} spinoza_freesurfer
    exit 1
  fi

  echo "---------------------------------------------------------------------------------------------------"
  echo "[${module}] Run FreeSurfer outside of fMRIprep"

  if [[ -d ${DIR_DATA_DERIV}/masked_${DATA,,} ]]; then
    INPUT_DIR=${DIR_DATA_DERIV}/masked_${DATA,,}
  elif [[ -d ${DIR_DATA_DERIV}/denoised ]]; then
    INPUT_DIR=${DIR_DATA_DERIV}/denoised
  elif [[ -d ${DIR_DATA_DERIV}/pymp2rage ]]; then
    INPUT_DIR=${DIR_DATA_DERIV}/pymp2rage
  else
    INPUT_DIR=${DIR_DATA_HOME}
  fi

  ${job} spinoza_freesurfer ${SUBJECT} ${SESSION} ${INPUT_DIR} all ${DIR_DATA_HOME}

  if [[ $? -ne 0 ]]; then
    echo "ERROR in master: spinoza_freesurfer exited with non-zero status"
    exit 1
  fi

  echo "[${module}] DONE" && echo

fi

#---------------------------------------------------------------------------------------------------
# STEP 15: Preprocess data with fMRIprep
module=15

# Check whether the module should be executed
echo ${FLAG_executeModule} | grep -q ${module}

if [[ $? -eq 0 ]]; then

  if [[ "${@}" == *"-q"* ]]; then
    ${job} spinoza_fmriprep
    exit 1
  fi

  echo "---------------------------------------------------------------------------------------------------"
  echo "[${module}] Preprocess session 1 data with fMRIprep"

  if [[ -z ${TYPE} ]]; then
    TYPE="anat"
  else
    TYPE=${TYPE}
  fi

  # decide on config file (overwrite earlier defaults)
  if [[ ! -z ${CONF} ]]; then
    if [[ ${CONF,,} == "none" ]]; then
      confFile=""
    else
      if [[ -f ${CONF} ]]; then
        confFile="-c ${CONF}"
      else
        echo "ERROR: Could not find config file \"${confFile}\""
        exit 1
      fi
    fi
  else
    confFile=""
  fi

  if [[ -d ${DIR_DATA_DERIV}/masked_${DATA,,} ]]; then
    ANAT_DIR=${DIR_DATA_DERIV}/masked_${DATA,,}
  else
    ANAT_DIR=${DIR_DATA_HOME}
  fi

  ${job} spinoza_fmriprep ${WARP_ONLY} ${use_bbr} ${run_local} ${SUBJECT} ${SESSION} ${confFile} ${REMOVE_WF} -f ${DIR_DATA_HOME} -m ${TYPE} ${ANAT_DIR} ${DIR_DATA_DERIV} ${DIR_DATA_HOME}

  if [[ $? -ne 0 ]]; then
    echo "ERROR in master: spinoza_fmriprep exited with non-zero status"
    exit 1
  fi

  echo "[${module}] DONE" && echo

fi

#---------------------------------------------------------------------------------------------------
# STEP 16: fMRI-data denoising with pybest using fmriprep's output
module=16

# Check whether the module should be executed
echo ${FLAG_executeModule} | grep -q ${module}

if [[ $? -eq 0 ]]; then

  if [[ "${@}" == *"-q"* ]]; then
    ${job} spinoza_denoising
    exit 1
  fi

  echo "---------------------------------------------------------------------------------------------------"
  echo "[${module}] Data denoising with pybest"

  if [[ ! -z ${TYPE} ]]; then
    TASK_ID="-t ${TYPE}"
  fi   

  ${job} spinoza_denoising ${raw_flag} ${SUBJECT} ${SESSION} ${SGE} ${OW} ${TASK_ID} ${DIR_DATA_DERIV}/fmriprep ${DIR_DATA_DERIV}/pybest

  if [[ $? -ne 0 ]]; then
    echo "ERROR in master: spinoza_denoising exited with non-zero status"
    exit 1
  fi

  echo "[${module}] DONE" && echo

fi

#---------------------------------------------------------------------------------------------------
# STEP 17: pRF-fitting with pRFpy
module=17

# Check whether the module should be executed
echo ${FLAG_executeModule} | grep -q ${module}

if [[ $? -eq 0 ]]; then

  if [[ "${@}" == *"-q"* ]]; then
    ${job} spinoza_fitprfs
    exit 1
  fi

  echo "---------------------------------------------------------------------------------------------------"
  echo "[${module}] pRF-fitting with pRFpy"

  # set model flag
  if [[ ! -z ${PRF_MODEL} ]]; then
    MODEL="-m ${PRF_MODEL}"
  fi

  # set PNG directory
  if [[ -z ${images} ]]; then
    PNG_DIR=${DIR_DATA_SOURCE}
  else
    PNG_DIR=${images}
  fi

  # set input directory depending on the presence of pybest output
  PRF_INPUT=${DIR_DATA_DERIV}/pybest
  if [[ ${fprep_input} -eq 1 ]]; then
    PRF_INPUT=${DIR_DATA_DERIV}/fmriprep
  fi

  # specify a specific task-ID to be fitted
  if [[ ! -z ${TYPE} ]]; then
    TASK_ID="-t ${TYPE}"
  fi  

  # set design clipper flag
  if [[ ! -z ${C_FLAG} ]]; then
    CLIP_FLAG="-c ${C_FLAG}"
  fi  

  # set constraints flag; note that 'use_constr' can also be set with '--tc' or '--bgfs'
  if [ ! -z ${KWARGS} ]; then
    use_constr="-x ${KWARGS}"
  fi

  ${job} spinoza_fitprfs ${use_constr} ${CLIP} ${CLIP_FLAG} ${verb_flag} ${zscore_flag} ${raw_flag} ${fit_flag} ${TASK_ID} ${FIT_HRF} ${run_local} ${GRID} ${MULTIPLE_DESIGNS} ${SUBJECT} ${SESSION} ${OW} ${MODEL} ${PRF_INPUT} ${DIR_DATA_DERIV}/prf ${PNG_DIR}

  if [[ $? -ne 0 ]]; then
    echo "ERROR in master: spinoza_fitprfs exited with non-zero status"
    exit 1
  fi

  echo "[${module}] DONE" && echo

fi

#---------------------------------------------------------------------------------------------------
# STEP 18: Determine best vertex with pycortex
module=18

# Check whether the module should be executed
echo ${FLAG_executeModule} | grep -q ${module}

if [[ $? -eq 0 ]]; then

  if [[ "${@}" == *"-q"* ]]; then
    ${job} spinoza_bestvertex
    exit 1
  fi

  echo "---------------------------------------------------------------------------------------------------"
  echo "[${module}] Determine best vertex with pycortex"

  if [[ ! -z ${VERTICES} ]]; then
    VERT="-v ${VERTICES}"
  fi

  if [[ ! -z ${ROI} ]]; then
    LABEL_FILE=${ROI}
  else
    LABEL_FILE="V1_exvivo.thresh"
  fi

  if [[ ! -z ${PRF_MODEL} ]]; then
    MODEL="-m ${PRF_MODEL}"
  fi

  if [[ ! -z ${TYPE} ]]; then
    TASK_ID="-t ${TYPE}"
  fi

  ${job} spinoza_bestvertex ${MODEL} ${TASK_ID} ${GRID} ${SUBJECT} ${SESSION} ${VERT} ${FREEVIEW} ${OW} ${DIR_DATA_HOME} ${DIR_DATA_DERIV} ${LABEL_FILE}

  if [[ $? -ne 0 ]]; then
    echo "ERROR in master: spinoza_bestvertex exited with non-zero status"
    exit 1
  fi

  echo "[${module}] DONE" && echo

fi

#---------------------------------------------------------------------------------------------------
# STEP 19: FAST segmentation with FSL
module=19

# Check whether the module should be executed
echo ${FLAG_executeModule} | grep -q ${module}

if [[ $? -eq 0 ]]; then

  if [[ "${@}" == *"-q"* ]]; then
    ${job} spinoza_segmentfast
    exit 1
  fi

  echo "---------------------------------------------------------------------------------------------------"
  echo "[${module}] FAST segmentation with FSL"

  ${job} spinoza_segmentfast ${SUBJECT} ${SESSION} ${OW} ${SKULLSTRIP} ${DIR_DATA_DERIV}/fsl

  if [[ $? -ne 0 ]]; then
    echo "ERROR in master: spinoza_segmentfast exited with non-zero status"
    exit 1
  fi

  echo "[${module}] DONE" && echo

fi

#---------------------------------------------------------------------------------------------------
# STEP 20: MGDM segmentation with nighres
module=20

# Check whether the module should be executed
echo ${FLAG_executeModule} | grep -q ${module}

if [[ $? -eq 0 ]]; then

  if [[ "${@}" == *"-q"* ]]; then
    ${job} spinoza_mgdm
    exit 1
  fi

  echo "---------------------------------------------------------------------------------------------------"
  echo "[${module}] MGDM segmentation with nighres"

  spinoza_mgdm ${SUBJECT} ${SESSION} ${OW} ${GDH_FLAG} ${DIR_DATA_DERIV}/skullstripped ${DIR_DATA_DERIV}/nighres ${DIR_DATA_DERIV}/manual_masks

  if [[ $? -ne 0 ]]; then
    echo "ERROR in master: spinoza_mgdm exited with non-zero status"
    exit 1
  fi

  echo "[${module}] DONE" && echo

fi

#---------------------------------------------------------------------------------------------------
# STEP 21: Region extraction with nighres
module=21

# Check whether the module should be executed
echo ${FLAG_executeModule} | grep -q ${module}

if [[ $? -eq 0 ]]; then

  if [[ "${@}" == *"-q"* ]]; then
    ${job} spinoza_extractregions
    exit 1
  fi

  echo "---------------------------------------------------------------------------------------------------"
  echo "[${module}] Region extraction with nighres"

  if [[ ! -z ${ROI} ]]; then
    ROI=${ROI}
  else
    ROI="cerebrum"
  fi

  ${job} spinoza_extractregions ${SUBJECT} ${SESSION} ${OW} ${COMB_ONLY} -f ${DIR_DATA_DERIV}/fmriprep ${DIR_DATA_DERIV}/nighres ${DIR_DATA_DERIV}/manual_masks ${ROI}

  if [[ $? -ne 0 ]]; then
    echo "ERROR in master: spinoza_extractregions exited with non-zero status"
    exit 1
  fi

  echo "[${module}] DONE" && echo

fi

#---------------------------------------------------------------------------------------------------
# STEP 22: Cortex reconstruction with nighres
module=22

# Check whether the module should be executed
echo ${FLAG_executeModule} | grep -q ${module}

if [[ $? -eq 0 ]]; then

  if [[ "${@}" == *"-q"* ]]; then
    ${job} spinoza_cortexrecon
    exit 1
  fi

  if [[ ! -z ${ROI} ]]; then
    ROI=${ROI}
  else
    ROI="cerebrum"
  fi

  echo "---------------------------------------------------------------------------------------------------"
  echo "[${module}] Cortex reconstruction with nighres"

  
  if [[ ${LAYER_FLAG} == "nighres" ]]; then
    PROBSEG=${DIR_DATA_DERIV}/nighres
  else
    PROBSEG=${DIR_DATA_DERIV}/manual_masks
  fi

  ${job} spinoza_cortexrecon ${SUBJECT} ${SESSION} ${OW} ${PROBSEG} ${DIR_DATA_DERIV}/nighres ${ROI}


  if [[ $? -ne 0 ]]; then
    echo "ERROR in master: spinoza_cortexrecon exited with non-zero status"
    exit 1
  fi

  echo "[${module}] DONE" && echo

fi

#---------------------------------------------------------------------------------------------------
# STEP 23: Equivolumetric layering with either nighres or Wagstyl's surface_tools
module=23

# Check whether the module should be executed
echo ${FLAG_executeModule} | grep -q ${module}

if [[ $? -eq 0 ]]; then

  if [[ "${@}" == *"-q"* ]]; then
    ${job} spinoza_layering
    exit 1
  fi

  echo "---------------------------------------------------------------------------------------------------"
  echo "[${module}] Equivolumetric layering"

  if [[ -z ${LAYER_FLAG} || ${LAYER_FLAG} == "nighres" ]]; then
    INPUT_DIR=${DIR_DATA_DERIV}/nighres
    SOFTWARE="nighres"
  elif [[ ${LAYER_FLAG} == "surface" ]]; then
    SOFTWARE="surface"
    INPUT_DIR=${FS}
  else
    echo "ERROR in `basename ${0}`: Unknown flag \"${LAYER_FLAG}\". Must be \"nighres\" or \"surface\""
    exit 1
  fi

  ${job} spinoza_layering ${SUBJECT} ${SESSION} ${INPUT_DIR} ${SOFTWARE}
  
  if [[ $? -ne 0 ]]; then
    echo "ERROR in master: spinoza_layering exited with non-zero status"
    exit 1
  fi

  echo "[${module}] DONE" && echo

fi

#---------------------------------------------------------------------------------------------------
# STEP 24: Subcortex parcellation with MASSP
module=24

# Check whether the module should be executed
echo ${FLAG_executeModule} | grep -q ${module}

if [[ $? -eq 0 ]]; then

  if [[ "${@}" == *"-q"* ]]; then
    ${job} spinoza_segmentsubcortex
    exit 1
  fi

  echo "---------------------------------------------------------------------------------------------------"
  echo "[${module}] Subcortex parcellation with MASSP"

  ${job} spinoza_segmentsubcortex ${SUBJECT} ${SESSION} ${DIR_DATA_HOME} ${DIR_DATA_DERIV}/skullstripped ${DIR_DATA_DERIV}/nighres

  if [[ $? -ne 0 ]]; then
    echo "ERROR in master: spinoza_segmentsubcortex exited with non-zero status"
    exit 1
  fi

  echo "[${module}] DONE" && echo

fi

#---------------------------------------------------------------------------------------------------
# STEP 25: Project line to surface with a registration cascade
module=25

# Check whether the module should be executed
echo ${FLAG_executeModule} | grep -q ${module}

if [[ $? -eq 0 ]]; then

  if [[ "${@}" == *"-q"* ]]; then
    ${job} spinoza_line2surface
    exit 1
  fi

  echo "---------------------------------------------------------------------------------------------------"
  echo "[${module}] Registration cascade to project line to surface"

  if [[ -z ${SUB} ]]; then
    echo "ERROR: Need a subject number for this module. Specify the subject number with the -s flag in the master script"
    echo "  e.g., ./master -m 24 -s 001"
    exit 1
  fi

  # input anat as defined in module 00
  ${job} spinoza_line2surface -s ${subject} -y ${DIR_DATA_HOME}/${subject}/ses-2/anat/${subject}_ses-2_acq-MP2RAGE_T1w.nii.gz -o ${CTX} -i ${NIGHRES}/${subject}/ses-2

  if [[ $? -ne 0 ]]; then
    echo "ERROR in master: spinoza_line2surface exited with non-zero status"
    exit 1
  fi

  echo "[${module}] DONE" && echo

fi

#---------------------------------------------------------------------------------------------------
# STEP 26: Project line to surface with a registration cascade
module=26

# Check whether the module should be executed
echo ${FLAG_executeModule} | grep -q ${module}

if [[ $? -eq 0 ]]; then

  if [[ "${@}" == *"-q"* ]]; then
    ${job} spinoza_profiling
    exit 1
  fi

  echo "---------------------------------------------------------------------------------------------------"
  echo "[${module}] Profile sampling using Nighres"

  if [[ -z ${KWARGS} ]]; then
    KWARGS="T2starmap"
  else
    KWARGS=${KWARGS}
  fi    

  # spinoza_profiling ${SUBJECT} ${SESSION} ${OW} ${DIR_DATA_DERIV}/nighres ${DIR_DATA_HOME} T1map
  ${job} spinoza_profiling ${SUBJECT} ${SESSION} ${OW} ${DIR_DATA_DERIV}/nighres ${DIR_DATA_HOME} ${KWARGS}

  if [[ $? -ne 0 ]]; then
    echo "ERROR in master: spinoza_segmentsubcortex exited with non-zero status"
    exit 1
  fi

  echo "[${module}] DONE" && echo

fi
