#!/usr/bin/env bash

#---------------------------------------------------------------------------------------------------------
# check if there's is a setup file containing the major paths and source it if it exists
echo
call_loadsetup

#---------------------------------------------------------------------------------------------------------
# Create help text
function Usage {
    cat <<USAGE

---------------------------------------------------------------------------------------------------
spinoza_sinusfrommni

This script takes the registration matrix from MNI to subject space to warp the sagittal sinus mask
in MNI-space to the subject space. We then multiply this image with the T1w/T2w ratio to get a de-
cent initial estimate of the sagittal sinus

Usage:
  spinoza_sinusfrommni [options] <anat folder> <registration folder> <mask folder>

Arguments:
  -s <subject>        subject ID (e.g., 01). Can also be comma-separated list: 01,02,05
  -n <session>        session ID (e.g., 1, 2, or none)
  -o                  Overwrite existing output
  <anat directory>    directory containing the T1w and T2w files; should generally be pymp2rage-
                      folder
  <registration>      path to directory where registration file is (output from spinoza_registration)
  <mask directory>    path to output mask directory (to put final 'sinus'-mask)

Eample:
  spinoza_sinusfrommni DIR_DATA_DERIV/pymp2rage DIR_DATA_DERIV/ants DIR_DATA_DERIV/manual_masks
  spinoza_sinusfrommni -s 001 -n 1 DIR_DATA_DERIV/pymp2rage DIR_DATA_DERIV/ants DIR_DATA_DERIV/manual_masks

---------------------------------------------------------------------------------------------------

USAGE
    exit 1
}

# Check for subject & session flags
OW=0
while getopts os:n: argument
do
  case ${argument} in
    s)  sub=${OPTARG}
          ;;
    n)  ses=${OPTARG}
          ;;
    o)  OW=1
          ;;          
  esac
done

if [[ $# -lt 2 ]] ; then
  Usage >&2
  exit 1
fi

ANAT=${@:$OPTIND:1}
MATRIX=${@:$OPTIND+1:1}
OUTPUT=${@:$OPTIND+2:1}

if [[ -z ${sub} ]]; then
  # loop through subjects
  search="${ANAT}/${PREFIX}*"
else
  # do for 1 subject
  sub_nr=`echo ${sub} | sed -e 's/^[[:space:]]*//'`
  search="${ANAT}/${PREFIX}${sub_nr}"
fi

#-----------------------------------------------------------------------------
# Start clock
#-----------------------------------------------------------------------------

echo "==================================================================================================="
printf "SAGITTAL SINUS FROM MNI AND T1W/T2W RATIO\n"
start=`date +%s`
start_date=`date`

printf "Started at ${start_date}\n"
echo "==================================================================================================="

#-----------------------------------------------------------------------------
# Run it

for dir in ${search}; do

  # check if we got a session number
  if [[ -z ${ses} ]]; then
    nr=""
    base=$(basename ${dir})
    base_dir=$(basename ${dir})
  else
    nr=`echo ${ses} | sed -e 's/^[[:space:]]*//'`
    base="$(basename ${dir})_ses-${nr}"
    base_dir=$(basename ${dir})/ses-${nr}
  fi

  pn_anat=${ANAT}/${base_dir}
  pn_matrix=${MATRIX}/${base_dir}
  pn_masks=${OUTPUT}/${base_dir}

  if [[ ! -d ${pn_masks} ]]; then
    mkdir -p ${pn_masks}
  fi

  if [[ -d ${pn_anat} ]]; then

    fn_ratio=${pn_anat}/${base}_acq-${DATA^^}_desc-ratio.nii.gz
    fn_nuisance=${pn_anat}/${base}_acq-${DATA^^}_desc-nuisance.nii.gz
    fn_mni=${pn_masks}/${base}_acq-${DATA^^}_space-MNI152NLin6Asym_desc-sinus.nii.gz
    fn_out=${pn_masks}/${base}_acq-${DATA^^}_desc-mni_sinus.nii.gz

    if [[ ${OW} -eq 1 ]]; then
      rm ${fn_ratio} ${fn_nuisance} ${fn_out} ${fn_mni} 2>/dev/null
      txt="Overwrite mode active"
    else
      txt="Overwrite mode inactive"
    fi

    if [[ ! -f ${fn_out} ]]; then

      if [[ ! -f ${fn_ratio} && ! -f ${fn_nuisance} ]]; then

        # calculate T1w/T2w ratio
        t1=`find "${pn_anat}" -type f \( -name "*T1w.nii.gz" \) 2>/dev/null`
        t2=`find "${pn_anat}" -type f \( -name "*T2w.nii.gz" \) 2>/dev/null`
        mask=`find "${pn_anat}" -type f \( -name "*spm_mask.nii.gz" \) 2>/dev/null`

        if [[ ! -z ${t1} && ! -z ${t2} ]]; then

          echo
          echo "**************************************** Processing `basename ${dir}` ***************************************"
          echo ${txt}

          # if we have a mask-image, we can create a sinus mask directly from the T2-image. Use ratio otherwise
          if [ ! -z ${mask} ]; then
            echo "Creating sinus mask directly from T2-image"
            fslmaths ${t2} -mas ${mask} $(dirname ${t2})/tmp_$(basename ${t2})
            fslmaths $(dirname ${t2})/tmp_$(basename ${t2}) -uthr 10000 -bin ${fn_nuisance}
            rm $(dirname ${t2})/tmp_$(basename ${t2}) 2>/dev/null
          else
            echo "Creating T1w/T2w + thresholded image"
            call_t12ratio --t1 ${t1} --t2 ${t2} -o ${pn_anat}/${base}_acq-${space^^}
          fi

          if [[ $? -ne 0 ]]; then
            echo "ERROR in `basename ${0}`: call_t12ratio exited with non-zero status"
            exit 1
          fi

        else
          echo "`basename ${dir}`: Could not find t1 and-/or t2 file input directory"
          continue
        fi

      fi

      if [[ ! -f ${fn_mni} ]]; then

        if [[ -f ${fn_nuisance} ]]; then

          # fetch template and warp files created with spinoza_registration in step before
          mni_mask=${DIR_SCRIPTS}/misc/MNI152_T1_1mm_Dil3_sagsinus_mask.nii.gz
          mat_file=`find "${pn_matrix}" -type f \( -name "*from-MNI152NLin6Asym*" -and -name "*.mat" \) 2>/dev/null`
          warp_file=`find "${pn_matrix}" -type f \( -name "*from-MNI152NLin6Asym*" -and -name "*invwarp.nii.gz" \) 2>/dev/null`
          
          if [[ ! -z ${mat_file} && ! -z ${warp_file} ]]; then
            echo "Warping MNI152_T1_1mm_Dil3_sagsinus_mask to subject space"

            call_antsapplytransforms -i "1 0" -t gen ${fn_nuisance} ${mni_mask} ${fn_mni} "${mat_file} ${warp_file}"

            if [[ $? -ne 0 ]]; then
              echo "ERROR in `basename ${0}`: call_antsapplytransforms exited with non-zero status"
              exit 1
            fi

          else
            echo "`basename ${dir}`: missing warp-files for call_antsapplytransforms"
            continue
          fi

        else
          echo "`basename ${dir}`: missing ${fn_nuisance}"
          continue
        fi

      fi

      if [[ ! -f ${fn_out} ]]; then
        if [[ -f ${fn_mni} ]]; then
          echo "Multiplying template mask with nuisance-image"
          fslmaths ${fn_mni} -mul ${fn_nuisance} ${fn_out}
          rm ${fn_mni} 2>/dev/null
          echo "Created ${fn_out}"

          if [[ $? -ne 0 ]]; then
            echo "ERROR in `basename ${0}`: fslmaths exited with non-zero status"
            exit 1
          fi

        else
          echo "`basename ${dir}`: Could not find file of MNI-mask in subject space. Check previous step!"
        fi
      fi

    else
      
      echo "`basename ${dir}`: `basename ${fn_out}` already exists"

    fi

  else

    echo "`basename ${dir}`: Could not find anatomy directory"
    continue

  fi

done

#-----------------------------------------------------------------------------
# Calculate time spent using 'let'
echo
echo "---------------------------------------------------------------------------------------------------"
end=`date +%s`
end_date=`date`
printf "Done at ${end_date}\n"

let deltatime=end-start
let hours=deltatime/3600
let minutes=(deltatime/60)%60
let seconds=deltatime%60
printf "Time spent: %d:%02d:%02d\n" ${hours} ${minutes} ${seconds}
echo "---------------------------------------------------------------------------------------------------"
