#!/usr/bin/env bash

#---------------------------------------------------------------------------------------------------------
# check if there's is a setup file containing the major paths and source it if it exists
call_loadsetup
source call_bashhelper

#---------------------------------------------------------------------------------------------------------
# Create help text
function Usage {
    cat <<USAGE

---------------------------------------------------------------------------------------------------
spinoza_dura

estimate the location of the skull and dura using nighres. You are to specify the path to the input
T1w-images (e.g., pymp2rage), the input INV2 image (e.g., the bias field corrected INV2 in the ANTs
folder, the nighres output folder, and the folder to store the masks.

Usage:
  spinoza_dura [options] <anat folder> <INV2 folder> <nighres output> <mask output>

Arguments:
  -s <subject>        subject ID (e.g., 01). Can also be comma-separated list: 01,02,05
  -n <session>        session ID (e.g., 1, 2, or n)
  -o                  overwrite existing files
  <anat directory>    folder containing the T1w-file
  <inv2 directory>    folder containing the INV2-image
  <nighres output>    output folder for Nighres
  <mask output>       output folder for masks

Example:
  spinoza_dura T1wdir INV2dir nighresdir maskdir
  spinoza_dura -s 001 -n 1 T1wdir INV2dir nighresdir maskdir

---------------------------------------------------------------------------------------------------

USAGE
    exit 1
}

# Check for subject & session flags
OW=0
while getopts os:n: argument
do
  case ${argument} in
    s)  sub=${OPTARG}
          ;;
    n)  ses=${OPTARG}
          ;;
    o)  OW=${OPTARG}
          ;;          
  esac
done

if [[ $# -lt 4 ]] ; then
  Usage >&2
  exit 1
fi

T1W=${@:$OPTIND:1}
INV2=${@:$OPTIND+1:1}
OUTPUT=${@:$OPTIND+2:1}
MASKS=${@:$OPTIND+3:1}

if [[ -z ${sub} ]]; then
  # loop through subjects
  search="${T1W}/${SUBJECT_PREFIX}*"
else
  # read specified subjects into array
  IFS=', ' read -r -a search <<< "${sub}"
  search=${search[@]}
  unset IFS
fi

#-----------------------------------------------------------------------------
# Start clock
#-----------------------------------------------------------------------------

echo
echo "==================================================================================================="
printf "NEW SKULL & DURA ESTIMATION USING NIGHRES\n"
start=`date +%s`
start_date=`date`

printf "Started at ${start_date}\n"
echo "==================================================================================================="

#-----------------------------------------------------------------------------
# Run it
for subID in ${search}; do

  # collect subject name
  if [[ ! -z ${sub} ]]; then
    sub_name=${SUBJECT_PREFIX}${subID}
    sub_id=${subID}
  else
    sub_name=$(basename ${subID})
    sub_id=`get_id ${sub_name} ${SUBJECT_PREFIX}`
  fi

  if [[ ! -z ${ses} ]]; then
    nr=`echo ${ses} | sed -e 's/^[[:space:]]*//'`
    base_path=${sub_name}/ses-${nr}
    base=${sub_name}_ses-${nr}
  else
    base_path=${sub_name}
    base=${sub_name}
  fi

  mask_dir=${MASKS}/${base_path}
  input_dir=${T1W}/${base_path}
  inv2_dir=${INV2}/${base_path}
  outdir_dura=${OUTPUT}/${base_path}/dura
  outdir_skull=${OUTPUT}/${base_path}/skullstrip

  echo
  echo "**************************************** Processing ${sub_name} ***************************************"

  # get INV2-image
  if [[ ${DATA} == "MP2RAGEME" ]]; then
    inv2=`find "${inv2_dir}" -type f \( -name "${sub_name}*" -and -name "*echo-1*" -and -name "*inv-2*" -and -name "*acq-${DATA^^}_*" -and -name "*part-mag*" -and -name "*.nii.gz" \) 2>/dev/null`      
    search_for=${DATA^^}
  else
    # take the MP2RAGE INV-2 if DATA == AVERAGE
    if [[ ${DATA} == "AVERAGE" ]]; then
      inv2=`find "${inv2_dir}" -type f \( -name "${sub_name}*" -and -not -name "*echo-*" -and -name "*inv-2*" -and -name "*acq-MP2RAGE_*" -and -name "*part-mag*" -and -name "*.nii.gz" \) 2>/dev/null`
    else
      inv2=`find "${inv2_dir}" -type f \( -name "${sub_name}*" -and -not -name "*echo-*" -and -name "*inv-2*" -and -name "*acq-${DATA^^}_*" -and -name "*part-mag*" -and -name "*.nii.gz" \) 2>/dev/null`
    fi
    search_for="MP2RAGE"
  fi

  # LOOK FOR THE T1W IMAGE
  t1w=`find "${input_dir}" -type f \( -name "${sub_name}*" -and -name "*acq-${DATA^^}*" -and -name "*T1w.nii.gz" \) 2>/dev/null`

  # LOOK FOR THE T1-MAP IMAGE
  t1map=`find "${input_dir}" -type f \( -name "*acq-${DATA^^}*" -and -name "*T1map.nii.gz" \) 2>/dev/null`

  #----------------------------------------------------------------------------------------------------------------------------------------------------------
  # Running dura mask module with call_nighresdura
  output_root="${base}_acq-${DATA^^}_desc"
	output_dura=${outdir_dura}/${output_root}-dura_proba.nii.gz
  output_mask=${MASKS}/${base_path}/${output_root}-dura_orig.nii.gz

  # check if we should overwrite
  if [[ ${OW} -eq 1 ]]; then
    rm ${output_mask} 2>/dev/null
  fi

  if [[ ! -f ${output_mask} ]]; then

    inv2_mask=`find "${mask_dir}" -type f \( -name "*${DATA^^}*" -and -name "*spm_mask.nii.gz" \) 2>/dev/null`

    if [[ -z ${inv2} ]]; then
      echo "${sub_name}: Missing INV2-image. Check ${inv2_dir} for:"
      echo " \"${sub_name}\""
      echo " \"echo-1\" (if DATA==MP2RAGEME)"
      echo " \"inv-2\""
      echo " \"${search_for}\""
      echo " \"part-mag\""
      continue
    fi

    if [[ -z ${t1w} ]]; then
      echo "No T1w-image in \"${input_dir}\""
      continue
    fi

    if [[ -z ${t1map} ]]; then
      echo "No T1map-image in \"${input_dir}\""
      continue
    fi

    if [[ -z ${inv2_mask} ]]; then
      echo "No brain mask \"*spm_mask\" in \"${mask_dir}\""
      continue
    fi

    if [[ ! -d ${outdir_dura} ]]; then
      mkdir -p ${outdir_dura}
    fi

    echo "Creating `basename ${output_mask}`"
    echo " -inv2: ${inv2}"
    echo " -mask: ${inv2_mask}"
    echo " -out:  ${outdir_dura}/${output_root}_dura-proba.nii.gz"

    # check if we should overwrite
    if [[ ${OW} -eq 1 ]]; then
      rm ${output_dura} 2>/dev/null
    fi

    if [[ ! -f ${output_dura} ]]; then

      if [[ ! -f ${outdir_dura}/${output_root}_dura-proba.nii.gz ]]; then
        echo "First running nighres to estimate the dura"

        if [[ -f ${inv2} && -d ${outdir_dura} ]]; then
          call_nighresdura -i "${inv2}" -m "${inv2_mask}" -o "${outdir_dura}" -b "${output_root}"

          if [[ -f ${outdir_dura}/${output_root}_dura-proba.nii.gz ]]; then
            mv ${outdir_dura}/${output_root}_dura-proba.nii.gz ${output_dura}
          fi

        else
          echo "Missing input files. Check if you ran spinoza_registration.sh before this"
          continue
        fi

      else
        echo "Found nighres output. Renaming it"
        mv ${outdir_dura}/${output_root}_dura-proba.nii.gz ${output_dura}
      fi

    fi

    echo "Thresholding and binarizing `basename ${output_dura}`"
    if [[ -f ${MASKS}/${base_path}/tmp_$(basename ${output_dura}) ]]; then
      rm ${MASKS}/${base_path}/tmp_$(basename ${output_dura})
    fi

    # thresholding
    if [[ -f ${output_dura} ]]; then
      fslmaths ${output_dura} -thr 0.8 ${MASKS}/${base_path}/tmp_$(basename ${output_dura})

      # binarizing
      fslmaths ${MASKS}/${base_path}/tmp_$(basename ${output_dura}) -bin ${output_mask}
      fslcpgeom ${inv2_mask} ${output_mask}

    else
      echo "Could not find nighres' dura output"
    fi

    # clearing out directory
    if [[ -f ${MASKS}/${base_path}/tmp_$(basename ${output_dura}) ]]; then
      rm ${MASKS}/${base_path}/tmp_$(basename ${output_dura})
    fi

  else
    echo "`basename ${output_mask}` already exists"
  fi

  #----------------------------------------------------------------------------------------------------------------------------------------------------------
  # Running skullstrip module with call_nighresskullstrip.py

	output_skullstrip=${outdir_skull}/${output_root}-strip_mask.nii.gz

  # check if we should overwrite
  if [[ ${OW} -eq 1 ]]; then
    rm ${output_skullstrip} 2>/dev/null
  fi

  if [[ ! -f ${output_skullstrip} ]]; then

    echo
    echo "Creating `basename ${output_skullstrip}`"

    if [[ -f ${t1w} && -f ${t1map} && -f ${inv2} ]]; then

      if [[ ! -d ${outdir_skull} ]]; then
        mkdir -p ${outdir_skull}
      fi

      output_skullnighres=${outdir_skull}/${output_root}_strip_mask.nii.gz
      if [[ ! -f ${output_skullnighres} ]]; then
        call_nighresskullstrip -i ${inv2} -t ${t1w} -m ${t1map} -o ${outdir_skull} -b ${output_root}
      else
        echo "Found nighres output for skullstripping module"
      fi

    else
      printf "Missing following file(s): "
			if [[ ! -f ${t1w} ]]; then
				echo "t1-weighted image "
			elif [[ ! -f ${t1map} ]]; then
				echo "t1map image"
			elif [[ ! -f ${inv2} ]]; then
				echo "2nd inversion image"
			else
				echo "multiple images not found"
			fi
			continue
    fi

    declare -a NIGH_OUT=(mask inv2 t1w t1map)
    for f in ${NIGH_OUT[@]}; do
      out=`find "${outdir_skull}" -type f \( -name "*${f}*" -and -name "*${DATA^^}*" \) 2>/dev/null`

      if [[ ! -f ${outdir_skull}/${output_root}-strip_${f}.nii.gz ]]; then
        if [[ ! -z ${out} ]]; then
          mv ${out} ${outdir_skull}/${output_root}-strip_${f}.nii.gz
          fslcpgeom ${inv2} ${outdir_skull}/${output_root}-strip_${f}.nii.gz
        else
          echo "Could not find file for mgdm output: ${f}"
        fi
      fi

    done

  fi

done

#-----------------------------------------------------------------------------
# Calculate time spent using 'let'
echo
echo "---------------------------------------------------------------------------------------------------"
end=`date +%s`
end_date=`date`
printf "Done at ${end_date}\n"

let deltatime=end-start
let hours=deltatime/3600
let minutes=(deltatime/60)%60
let seconds=deltatime%60
printf "Time spent: %d:%02d:%02d\n" ${hours} ${minutes} ${seconds}
echo "---------------------------------------------------------------------------------------------------"
