#!/usr/bin/env bash

#---------------------------------------------------------------------------------------------------------
# check if there's is a setup file containing the major paths and source it if it exists
echo
call_loadsetup
source call_bashhelper

#---------------------------------------------------------------------------------------------------------
# Create help text
function Usage {
    cat <<USAGE

---------------------------------------------------------------------------------------------------
spinoza_denoising

wrapper for call_pybest that does the denoising of fMRI-data based on the confound file created
during the preprocessing with fmriprep. By default, it will use FSNative, unless the PYBEST_SPACE
variable in the setup file says something else, or if the '--fsaverage' flag is specified

Usage:
  spinoza_denoising [options] <fmriprep directory> <pybest output directory>

Arguments:
  -s <subject>        subject ID (e.g., 01). Can also be comma-separated list: 01,02,05
  -n <session>        session ID (e.g., 1, 2, or none)
  -t <task ID>        limit pybest processing to a specific task. Default is all tasks in TASK_SES1
                      in the spinoza_setup-file
  -o|--ow             overwrite existing files
  -c|--sge            submit job to cluster (called with 'master -m <module> --sge')
  --no_raw            do NOT unzscore the output from pybest (default is to do so)
  --fsaverage         overwrite PYBEST_SPACE-variable and use FSAverage for pybest (defaults to fs-
                      native)
  --fsnative          overwrite PYBEST_SPACE-variable and use FSNative for pybest (defaults to fs-
                      native)
  <project root>      base directory containing the derivatives and the subject's folders.
  <derivatives>       path to the derivatives folder

Eample:
  spinoza_denoising DIR_DATA_HOME DIR_DATA_DERIV
  spinoza_denoising -s 001 -n 1 DIR_DATA_HOME DIR_DATA_DERIV
  spinoza_denoising -o DIR_DATA_HOME DIR_DATA_DERIV

---------------------------------------------------------------------------------------------------

USAGE
    exit 1
}

# Check for subject & session flags
OW=0
job="bash"
cpu=1
task_flag=""
raw_flag=""
smp=1
SGE=0

# check if variable is set in setup file
if [[ -z ${PYBEST_SPACE} ]]; then
  PYBEST_SPACE="fsnative"
fi

while getopts :-:os:n:t::c argument
do
  case ${argument} in
    -)
      case "${OPTARG}" in
        no_raw)
          raw_flag="--no_raw"
          ;;
        ow)
          OW=1
          ;;          
        sge)
          SGE=1
          ;;          
        fsaverage)
          PYBEST_SPACE="fsaverage"
          ;; 
        fsnative)
          PYBEST_SPACE="fsnative"
          ;;                     
        *)
          if [ "$OPTERR" = 1 ] && [ "${optspec:0:1}" != ":" ]; then
            echo "Unknown option --${OPTARG}"
            exit 1
          fi
          ;;
      esac;;     
    s)  sub=${OPTARG}
          ;;
    n)  ses=${OPTARG}
          ;;
    o)  OW=1
          ;;         
    c)  SGE=1
          ;;
    t)  task_flag="-t ${OPTARG}" 
          ;;
  esac
done

if [[ $# -lt 2 ]] ; then
  Usage >&2
  exit 1
fi

if [[ ${SGE} -eq 1 ]]; then
  job="qsub -q ${SGE_QUEUE_LONG} -wd ${DIR_LOGS} -pe smp ${smp}"
  cpu=10
  if [ ! -d ${DIR_LOGS} ]; then
    mkdir -p ${DIR_LOGS}
  fi
fi

# fetch positional arguments
FPREP=${@:$OPTIND:1}
DENOISE=${@:$OPTIND+1:1}

if [[ -z ${sub} ]]; then
  # loop through subjects
  search="${FPREP}/${SUBJECT_PREFIX}*"
else
  # read specified subjects into array
  IFS=', ' read -r -a search <<< "${sub}"
  search=${search[@]}
  unset IFS
fi

#-----------------------------------------------------------------------------
# Start clock
#-----------------------------------------------------------------------------

echo "==================================================================================================="
printf "DENOISING DATA WITH FMRIPREP-CONFOUNDS\n"
start=`date +%s`
start_date=`date`

printf "Started at ${start_date}\n"
echo "==================================================================================================="

#-----------------------------------------------------------------------------
# Run it
for subID in ${search}; do

  if [[ ${subID} != *"html"* ]]; then

    # collect subject name
    if [[ ! -z ${sub} ]]; then
      sub_name=${SUBJECT_PREFIX}${subID}
      sub_id=${subID}
    else
      sub_name=$(basename ${subID})
      sub_id=`get_id ${sub_name} ${SUBJECT_PREFIX}`
    fi

    if [[ ! -z ${ses} ]]; then
      nr=`echo ${ses} | sed -e 's/^[[:space:]]*//'`
      base_path=${sub_name}/ses-${nr}
      base=${sub_name}_ses-${nr}
    else
      base_path=${sub_name}
      base=${sub_name}
    fi

    if [[ ${OW} -eq 1 ]]; then
      # overwrite mode enabled
      if [[ -d ${DENOISE}/${base_path} ]]; then
        rm -r ${DENOISE}/${base_path}
      fi
    fi

    if [[ ! -d ${DENOISE} ]]; then
      mkdir -p ${DENOISE}
    fi

    if [[ -d ${FPREP}/${base_path}/func ]]; then

      if [[ ! -d ${DENOISE}/${base_path}/denoising ]]; then

        echo
        echo "**************************************** Processing ${sub_name} ***************************************"

        # append sub
        if [[ ${job} != "bash" ]]; then
          job="${job} -N ${base}_desc-pybest"
        fi

        # full path is needed for qsub
        ${job} ${DIR_SCRIPTS}/bin/call_pybest \
          -s ${sub_id} \
          -n ${nr} \
          -o ${DENOISE} \
          -r ${PYBEST_SPACE} \
          -f ${FPREP} \
          -c ${cpu} \
          -p ${PYBEST_N_COMPS} \
          ${task_flag} \
          ${raw_flag}

        if [[ $? != 0 ]]; then
          echo
          echo "---------------------------------------------------------------------------------------------------"
          echo "ERROR in `basename ${0}`: call_pybest exited with non-zero status"
          exit 1
        fi        

      else
        echo "${sub_name}: data already denoised"
      fi

    else
      echo "${sub_name}: directory \"${FPREP}/${base_path}/func\" does not exist. Run and/or wait for fMRIprep first.."
      continue
    fi

  fi

done

#-----------------------------------------------------------------------------
# Calculate time spent using 'let'
echo
echo "---------------------------------------------------------------------------------------------------"
end=`date +%s`
end_date=`date`
printf "Done at ${end_date}\n"

let deltatime=end-start
let hours=deltatime/3600
let minutes=(deltatime/60)%60
let seconds=deltatime%60
printf "Time spent: %d:%02d:%02d\n" ${hours} ${minutes} ${seconds}
echo "---------------------------------------------------------------------------------------------------"
