#!/usr/bin/env bash

SETUP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SETUP_FILE="${SETUP_DIR}/spinoza_setup"
REPO_DIR=$(dirname ${SETUP_DIR})
PATH_HOME=$(dirname $(dirname ${SETUP_DIR}))
export PATH_HOME=${PATH_HOME}

if [[ $1 == "setup" ]]; then

  echo
  echo "---------------------------------------------------------------------------------------------------------"
  echo "Welcome to the linescanning-repository!"
  echo
  echo "Execute the following steps to setup the repository:"
  echo " 1) Hit \"master\" in the terminal; if all went well this should bring up the help-menu"
  echo " 2) Hit \"cd $(dirname ${REPO_DIR})\""
  echo " 3) If you have sudo-right, do \"sudo python setup.py develop\", if not: \"python setup.py develop --user\""
  echo " 4) Enter \"ipython\" and then \"from linescanning import *\". No error means SUCCESS!"
  echo " 5) Go to line 87 and specify where your projects are. Default is set to:"
  echo "    \"${PATH_HOME}/projects\""
  echo "---------------------------------------------------------------------------------------------------------"
  echo

  # ignore permission changes in git
  git config core.fileMode false

  # make scripts executable
  chmod -R 775 ${REPO_DIR}/bin
  chmod -R 775 ${REPO_DIR}/shell

  if [ -f ~/.bash_profile ]; then
    search_for="source ${SETUP_FILE}"
    case `grep -Fx "${search_for}" ~/.bash_profile >/dev/null; echo $?` in
      0)
        # code if found
        # echo "Line already present"
        ;;
      1)
        # code if not found
        (
        echo 
        echo "# Inserted via the linescanning-repository"
        echo "source ${SETUP_FILE}"
        echo "echo \"ACTIVE PROJECT    ${DIR_DATA_HOME}\""
        echo "echo \"ACTIVE ACQ FORMAT ${DATA}\""
        ) >> ~/.bash_profile
        ;;
      *)
        # code if an error occurred
        echo "ERROR: Could not complete setup.."
        ;;
    esac
  else
      (
      echo "# .bash_profile"
      echo "# Inserted via the linescanning-repository"
      echo "source ${SETUP_FILE}"
      echo "echo \"ACTIVE PROJECT    ${DIR_DATA_HOME}\""
      echo "echo \"ACTIVE ACQ FORMAT ${DATA}\""
      ) >> ~/.bash_profile
  fi

  source ~/.bash_profile

fi

#===================================================================================================
# VARIABLES
#===================================================================================================

# If you have access to SGE, leave to SGE; otherwise change to e.g., LOCAL
export PLACE=SGE

# MATLAB
export MRRECON=/packages/matlab/toolbox/MRecon/3.0.541  
export MATLAB_DIR=/packages/matlab/R2020b               
export SPM_PATH=${PATH_HOME}/programs/packages/spm12    
export SKIP_LINES=30                                    

# fMRIPREP
export MRIQC_SIMG=${PATH_HOME}/programs/packages/mriqc/containers_bids-mriqc--0.15.1.simg
export FPREP_SIMG=${PATH_HOME}/programs/packages/fmriprep/containers_bids-fmriprep--20.2.5.simg
export FPREP_OUT_SPACES="fsnative fsaverage MNI152NLin6Asym:res-1"
export FPREP_BINDING="/data1/projects" # binding directory for singularity image
export CIFTI=170k # leave empty if you don't want cifti output
export DO_SYN=1 # set to zero if you do not want additional syn-distortion correction

# PYBEST
export PYBEST_SPACE="fsnative"
export PYBEST_NORM="zscore"

# PROJECT
export DIR_PROJECTS=$(dirname $(dirname ${PATH_HOME}))/projects 
export PROJECT=hemifield # ANAT_SEG-Raw #URIS-MDD #hemifield
export TASK_SES1="2R"
export TASK_SES2="LR"
export PREFIX="sub-"

# DATA TYPE(S)
declare -a ACQ=("MP2RAGE") # or ("MP2RAGE" "MEMP2RAGE")
export DATA=${ACQ[0]} # or MP2RAGEME/AVERAGE

# For DATA == AVERAGE we'll need multiple acquisitions
if [[ ${DATA} == "AVERAGE" ]]; then
  if [[ `echo ${#ACQ[@]}` -ne 2 ]]; then
    echo "Average of what..? \"ACQ\" variable in spinoza_setup has ${#ACQ[@]} items"
    exit 1
  fi
fi

#===================================================================================================
# PATHS
#===================================================================================================

export DIR_SCRIPTS=${REPO_DIR}
export DIR_DATA_HOME=${DIR_PROJECTS}/${PROJECT}
export DIR_LOGS=${DIR_DATA_HOME}/code/logs
export DIR_DATA_SOURCE=${DIR_DATA_HOME}/sourcedata
export DIR_DATA_DERIV=${DIR_DATA_HOME}/derivatives
export DIR_DATA_ATLAS=${PATH_HOME}/atlas/MICCAI2012-Multi-Atlas-Challenge-Data
export SOURCEDATA=${DIR_DATA_HOME}
export DERIVATIVES=${DIR_DATA_DERIV}
export MASKS=${DIR_DATA_DERIV}/manual_masks
export ANTS=${DIR_DATA_DERIV}/ants
export FS=${DIR_DATA_DERIV}/freesurfer
export ANTS=${DIR_DATA_DERIV}/ants
export AVG=${DIR_DATA_DERIV}/average
export MASKED_AVG=${DIR_DATA_DERIV}/masked_average
export PYMP2RAGE=${DIR_DATA_DERIV}/pymp2rage
export NIGHRES=${DIR_DATA_DERIV}/nighres
export FSL=${DIR_DATA_DERIV}/fsl
export SKULLSTRIP=${DIR_DATA_DERIV}/skullstripped
export CTX=${DIR_DATA_DERIV}/pycortex
export PRF=${DIR_DATA_DERIV}/prf

# Make executables available in environment
export PATH=${PATH}:${DIR_SCRIPTS}/bin
export PATH=${PATH}:${DIR_SCRIPTS}/shell

# chmod -R 775 ${DIR_SCRIPTS}/bin
# chmod -R 775 ${DIR_SCRIPTS}/shell

# Store acquisitions file file in data folder
if [[ -f ${DIR_SCRIPTS}/misc/acq.txt ]]; then
  rm -r ${DIR_SCRIPTS}/misc/acq.txt 2>/dev/null
fi

touch ${DIR_SCRIPTS}/misc/acq.txt
j=0
for i in `seq 1 ${#ACQ[@]}`; do
  echo "ACQ${i}=${ACQ[j]}" >> ${DIR_SCRIPTS}/misc/acq.txt
  (( j++ ))
done

while IFS= read -r line; do export ${line}; done < ${DIR_SCRIPTS}/misc/acq.txt
# source ${DIR_SCRIPTS}/bin/utils/acq.txt

# set SSH_KEY for start_ssh
export SSH_KEY="${HOME}/.ssh/hp_windows"

# source bash helper functions
source call_bashhelper