#!/usr/bin/env bash

#---------------------------------------------------------------------------------------------------------
# check if there's is a setup file containing the major paths and source it if it exists
call_loadsetup
source call_bashhelper

#---------------------------------------------------------------------------------------------------------
# Create help text
function Usage {
    cat <<USAGE

---------------------------------------------------------------------------------------------------
spinoza_mgdm

Tissue segmentation using nighres' MGDM. It assumes that you've run module from this pipeline before,
so that you're directory structure is like derivatives/<process>/${SUBJECT_PREFIX}xxx/ses-x. For this script, you
need to give the path to the skullstripped directory up until ${SUBJECT_PREFIX}xxx, the output mgdm directory,
and the directory containing masks that are used to filter out stuff in the MGDM segmentation.

By default, it's set to overwrite existing files in order to be able to iterate over the structural
preprocessing pipeline for optimizing the segmentations. To disable, run this particular module with
the overwrite switch set to 'n': master -m <module> -o n

Usage:
  spinoza_mgdm [options] <skullstripped> <mgdm> <masks>

Arguments:
  -s <subject>        subject ID (e.g., 01). Can also be comma-separated list: 01,02,05
  -n <session>        session ID (e.g., 1, 2, or none)
  -o|--ow             overwrite existing files
  --gdh               run GdH-pipeline version (call_gdhmgdm). 
  -j <n_cpus>         number of CPUs to use (default = 1)
  -q <queue>          submit jobs to a specific queue. Defaults to SGE_QUEUE_LONG in spinoza_setup
  --sge               submit job to cluster (SGE)

  Default = regular MGDM
  <skullstripped>     path to skullstripped data
  <mgdm>              path to output directory
  <masks>             path to masks

Example:
  spinoza_mgdm SKULLSTRIP NIGHRES/mgdm MASKS
  spinoza_mgdm -s 001 -n 1 SKULLSTRIP NIGHRES/mgdm MASKS
  spinoza_mgdm -s 001 -n 1 --gdh SKULLSTRIP NIGHRES/mgdm MASKS

---------------------------------------------------------------------------------------------------

USAGE
    exit 1
}

if [[ $# -lt 2 ]] ; then
  Usage >&2
  exit 1
fi

# Check for subject & session flags
OW=0
type=""
SGE=0
n_cpus=1
while getopts :-:os:n:t:q:j: argument
do
  case ${argument} in
    -)
      case "${OPTARG}" in
        gdh)
          type="gdh"
          ;;                  
        ow)
          OW=1
          ;;
        sge)
          SGE=1
          ;;                                     
        *)
          if [ "$OPTERR" = 1 ] && [ "${optspec:0:1}" != ":" ]; then
            echo "Unknown option --${OPTARG}"
            exit 1
          fi
          ;;
      esac;;   
    s)  sub=${OPTARG}
          ;;
    n)  ses=${OPTARG}
          ;;
    t)  type=${OPTARG}
          ;;
    o)  OW=1
          ;;     
    j)  n_cpus=${OPTARG}
          ;;
    q)  SGE_QUEUE=${OPTARG}
          ;;                 
  esac
done

if [[ $# -lt 4 ]] ; then
  Usage >&2
  exit 1
fi

INPUT=${@:$OPTIND:1}
OUTPUT=${@:$OPTIND+1:1}
MASKS=${@:$OPTIND+2:1}

if [[ -z ${sub} ]]; then
  # loop through subjects
  search="${INPUT}/${SUBJECT_PREFIX}*"
else
  # read specified subjects into array
  IFS=', ' read -r -a search <<< "${sub}"
  search=${search[@]}
  unset IFS
fi

#-----------------------------------------------------------------------------
# Start clock
#-----------------------------------------------------------------------------

echo
echo "==================================================================================================="
printf "NEW MGDM SEGMENTATION WITH NIGHRES\n"
start=`date +%s`
start_date=`date`

printf "Started at ${start_date}\n"
echo "==================================================================================================="

#-----------------------------------------------------------------------------
# Run it
for subID in ${search}; do

  # collect subject name
  if [[ ! -z ${sub} ]]; then
    sub_name=${SUBJECT_PREFIX}${subID}
    sub_id=${subID}
  else
    sub_name=$(basename ${subID})
    sub_id=`get_id ${sub_name} ${SUBJECT_PREFIX}`
  fi

  if [[ ! -z ${ses} ]]; then
    nr=`echo ${ses} | sed -e 's/^[[:space:]]*//'`
    base_path=${sub_name}/ses-${nr}
    base=${sub_name}_ses-${nr}
  else
    base_path=${sub_name}
    base=${sub_name}
  fi

  input_dir=${INPUT}/${base_path}
  output_dir=${OUTPUT}/${base_path}
  mask_dir=${MASKS}/${base_path}

  #----------------------------------------------------------------------------------------------------------------------------------------------
  # Look for files
  bet_uni=`find "${input_dir}" -type f \( -name "*acq-${DATA^^}*" -and -not -name "*gdh*" -and -name "*T1w.nii.gz" \) 2>/dev/null`
  bet_t1m=`find "${input_dir}" -type f \( -name "*acq-${DATA^^}*" -and -not -name "*gdh*" -and -name "*T1map.nii.gz" \) 2>/dev/null`
  mask_outside=`find "${mask_dir}" -type f \( -name "*acq-${DATA^^}*" -and -name "*-outside*" -and -name "*.nii.gz" \) 2>/dev/null`

  # Define nighres output names
  output_root="${base}_acq-${DATA^^}_desc"
  masked_seg=${output_dir}/mgdm
  mgdm_seg=${masked_seg}/${output_root}-mgdm_seg.nii.gz

  # OVERWRITE ALL CREATED FILES; SHOULD BE DEFAULT AND CAN BE DISABLE BY SPECIFYING MASTER -M <MODULE> -O N
  if [[ ${OW} -eq 1 ]]; then
    # txt="Overwrite mode: deleting files with \"${output_root}\""
    if [[ -d ${masked_seg} ]]; then
      rm -r ${masked_seg}/${output_root}* 2>/dev/null
    fi
  fi

  # if we want the GdH-mgdm script, run it directly.
  execute_cmd=0
  if [[ ${type} == "gdh" ]]; then
    if [[ ! -f ${mgdm_seg} ]]; then
      execute_cmd=1

      run_mode="Running GhD-version of MGDM with call_gdhmgdm"
      if [[ ${SGE} -eq 1 ]]; then
        run_cmd="${DIR_SCRIPTS}/bin/call_gdhmgdm"
      else
        run_cmd="call_gdhmgdm"
      fi

      if [[ ! -f ${mask_outside} ]]; then
        reason="Could not find \"outside\" mask.. [GdH]"
        execute_cmd=0
      fi

      fs_mask=${SUBJECTS_DIR}/${sub_name}/mri/brainmask.mgz
      brainmask=`find -L "${input_dir}" -type f \( -name "mask*" -and -name "*acq-${DATA^^}*" \) 2>/dev/null`
      if [[ -f ${fs_mask} ]]; then
        use_mask="fs"
      else
        if [[ ! -z ${brainmask} ]]; then
          use_mask=${brainmask}
        else
          reason="not sure what mask to use.. [GdH]"
          execute_cmd=0
        fi
      fi

      cmd="""${run_cmd} \
        -s ${sub_name} \
        -n ${nr} \
        -a ${input_dir} \
        -b ${use_mask} \
        -d ${mask_outside} \
        -o ${masked_seg}"""

    else
      reason="segmentation already present [GdH]"
    fi
  else

    if [[ ! -d $(dirname ${mgdm_seg}) ]]; then
      mkdir -p $(dirname ${mgdm_seg})
    fi

    if [[ ! -f ${mgdm_seg} ]]; then

      execute_cmd=1
      run_mode="Running regular version of MGDM with call_nighresmgdm"

      if [[ -z ${bet_uni} ]]; then
        execute_cmd=0
        reason="Could not find skullstripped T1-image.. "
      fi

      if [[ -z ${bet_t1m} ]]; then
        execute_cmd=0
        reason="Could not find skullstripped T1map-image.. "
      fi

      if [[ ${SGE} -eq 1 ]]; then
        run_cmd="${DIR_SCRIPTS}/bin/call_nighresmgdm"
      else
        run_cmd="call_nighresmgdm"
      fi

      cmd="""${run_cmd} \
        -t ${bet_uni} \
        -m ${bet_t1m} \
        -o ${masked_seg} \
        -b ${output_root}"""

    else
      execute_cmd=0
      reason="segmentation already present"
    fi
  fi

  if [[ ${execute_cmd} -eq 1 ]]; then
    if [[ ${SGE} -eq 0 ]]; then

      echo
      echo "**************************************** Processing ${sub_name} ***************************************"
      echo ${run_mode}
      echo "Creating `basename ${mgdm_seg}`"
    fi

    if [[ ${SGE} -eq 1 ]]; then
      if [[ ! -z ${SGE_QUEUE} ]]; then
        QUEUE=${SGE_QUEUE}
      else
        QUEUE=${SGE_QUEUE_SHORT}
      fi            
      job="qsub -q ${QUEUE} -wd ${DIR_LOGS} -pe smp ${n_cpus} -N ${output_root}-nighres_mgdm"
    else
      job=""
    fi

    final_cmd="""${job} ${cmd}"""
    if [[ ${SGE} -eq 0 ]]; then
      echo ${final_cmd}
    fi

    # execute command
    ${final_cmd}

    if [[ $? != 0 ]]; then
      echo
      echo "---------------------------------------------------------------------------------------------------"
      echo "ERROR in `basename ${0}`: ${run_cmd} exited with non-zero status"
      exit 1
    fi

  else
    echo "${sub_name}: Not executing MGDM; ${reason}"
  fi
done

#-----------------------------------------------------------------------------
# Calculate time spent using 'let'
echo
echo "---------------------------------------------------------------------------------------------------"
end=`date +%s`
end_date=`date`
printf "Done at ${end_date}\n"

let deltatime=end-start
let hours=deltatime/3600
let minutes=(deltatime/60)%60
let seconds=deltatime%60
printf "Time spent: %d:%02d:%02d\n" ${hours} ${minutes} ${seconds}
echo "---------------------------------------------------------------------------------------------------"
