version: 2

conda:
  environment: environment.yml

build:
  jobs:
    pre_create_environment:
      - echo "Command run at 'pre_create_environment' step"
    post_build:
      - echo "Command run at 'post_build' step"
      - echo `date`

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: conf.py
